@startuml
actor Administrador as AD
collections "Sesion de\nusuario" as SU
collections "Solicitar pedido\ny requerimiento" as SR
entity vendedor as  VD
boundary AppCntrolador as AC
collections "crear y procesar\npedido completo" as CP
boundary AppVista as AV
database Base_de_Datos as DB


AD --> DB : [001] CreaPerfilUsuario()
group Iniciar Sesión
AD --> SU: [002] IniciarSesion()
SU --> AD : [003] CredencialesCorrectas()
end group
AD--> SR :[004]RegistrarRequerimientoPedido()
SR--> VD :[005]RecepcionaRequerimientoPedido()
SR--> AC :[006]RecepcionaRequerimientoPedido()
group Validar Pedido Completo
VD --> CP: [007] Procesar PedidoCompleto()
AC --> CP :[008] Procesar PedidoCompleto()
VD <-- CP :[009] ErrorPedido()
AC <-- CP :[010] ErrorPedido()
end group
CP --> AV :[011]EntregarPedido()
AV --> DB :[012]RegistrarPedido()
DB --> AD:[013]NotificarPedido()
@enduml

